# Generated by Django 5.2.5 on 2025-08-18 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roktodanbdweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+880199999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('house_holding_no', models.CharField(max_length=100)),
                ('road_block', models.CharField(max_length=200)),
                ('thana', models.CharField(choices=[('Adabar', 'Adabar'), ('Badda', 'Badda'), ('Banani', 'Banani'), ('Baridhara', 'Baridhara'), ('Dhanmondi', 'Dhanmondi'), ('Gulshan', 'Gulshan'), ('Hatirjheel', 'Hatirjheel'), ('Kafrul', 'Kafrul'), ('Kalabagan', 'Kalabagan'), ('Khilgaon', 'Khilgaon'), ('Khilkhet', 'Khilkhet'), ('Mirpur', 'Mirpur'), ('Mohammadpur', 'Mohammadpur'), ('Motijheel', 'Motijheel'), ('New Market', 'New Market'), ('Old Dhaka', 'Old Dhaka'), ('Pallabi', 'Pallabi'), ('Ramna', 'Ramna'), ('Rampura', 'Rampura'), ('Sabujbagh', 'Sabujbagh'), ('Shah Ali', 'Shah Ali'), ('Sher-e-Bangla Nagar', 'Sher-e-Bangla Nagar'), ('Tejgaon', 'Tejgaon'), ('Uttara', 'Uttara'), ('Wari', 'Wari')], max_length=50)),
                ('post_office', models.CharField(choices=[('Dhaka GPO', 'Dhaka GPO'), ('Banani', 'Banani'), ('Dhanmondi', 'Dhanmondi'), ('Gulshan', 'Gulshan'), ('Mirpur', 'Mirpur'), ('Mohammadpur', 'Mohammadpur'), ('Motijheel', 'Motijheel'), ('New Market', 'New Market'), ('Old Dhaka', 'Old Dhaka'), ('Ramna', 'Ramna'), ('Tejgaon', 'Tejgaon'), ('Uttara', 'Uttara'), ('Wari', 'Wari')], max_length=50)),
                ('district', models.CharField(choices=[('Dhaka', 'Dhaka')], default='Dhaka', max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipient_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
                'ordering': ['-created_at'],
            },
        ),
    ]
