# Generated by Django 5.2.5 on 2025-08-23 22:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roktodanbdweb', '0003_recipient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['-registration_date'], 'verbose_name': 'Donor', 'verbose_name_plural': 'Donors'},
        ),
        migrations.RemoveField(
            model_name='donor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='state',
        ),
        migrations.AddField(
            model_name='donor',
            name='consent_declaration',
            field=models.BooleanField(default=False, help_text='Consent to donate blood'),
        ),
        migrations.AddField(
            model_name='donor',
            name='health_declaration',
            field=models.BooleanField(default=False, help_text='Declared good health in past 3 months'),
        ),
        migrations.AddField(
            model_name='donor',
            name='house_holding_no',
            field=models.CharField(default='N/A', help_text='House holding number', max_length=50),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the donor profile is active'),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether the donor is currently available for donation'),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last profile update'),
        ),
        migrations.AddField(
            model_name='donor',
            name='medication_declaration',
            field=models.BooleanField(default=False, help_text='Not taking medications affecting donation'),
        ),
        migrations.AddField(
            model_name='donor',
            name='post_office',
            field=models.CharField(choices=[('Dhaka GPO', 'Dhaka GPO'), ('Banani', 'Banani'), ('Dhanmondi', 'Dhanmondi'), ('Gulshan', 'Gulshan'), ('Mirpur', 'Mirpur'), ('Mohammadpur', 'Mohammadpur'), ('Motijheel', 'Motijheel'), ('New Market', 'New Market'), ('Old Dhaka', 'Old Dhaka'), ('Ramna', 'Ramna'), ('Tejgaon', 'Tejgaon'), ('Uttara', 'Uttara'), ('Wari', 'Wari')], default='Dhaka GPO', help_text='Nearest post office', max_length=50),
        ),
        migrations.AddField(
            model_name='donor',
            name='road_block',
            field=models.CharField(default='N/A', help_text='Road or block name/number', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='thana',
            field=models.CharField(choices=[('Adabar', 'Adabar'), ('Badda', 'Badda'), ('Banani', 'Banani'), ('Baridhara', 'Baridhara'), ('Dhanmondi', 'Dhanmondi'), ('Gulshan', 'Gulshan'), ('Hatirjheel', 'Hatirjheel'), ('Kafrul', 'Kafrul'), ('Kalabagan', 'Kalabagan'), ('Khilgaon', 'Khilgaon'), ('Khilkhet', 'Khilkhet'), ('Mirpur', 'Mirpur'), ('Mohammadpur', 'Mohammadpur'), ('Motijheel', 'Motijheel'), ('New Market', 'New Market'), ('Old Dhaka', 'Old Dhaka'), ('Pallabi', 'Pallabi'), ('Ramna', 'Ramna'), ('Rampura', 'Rampura'), ('Sabujbagh', 'Sabujbagh'), ('Shah Ali', 'Shah Ali'), ('Sher-e-Bangla Nagar', 'Sher-e-Bangla Nagar'), ('Tejgaon', 'Tejgaon'), ('Uttara', 'Uttara'), ('Wari', 'Wari')], default='Dhaka', help_text='Thana/Police station', max_length=50),
        ),
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Associated user account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donor',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=60.0, help_text='Weight in kg (minimum 50kg required for donation)', max_digits=5, validators=[django.core.validators.MinValueValidator(50.0)]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.PositiveIntegerField(help_text='Age must be between 18 and 65 years', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text="Donor's blood group", max_length=3),
        ),
        migrations.AlterField(
            model_name='donor',
            name='district',
            field=models.CharField(default='Dhaka', help_text='District name', max_length=50),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_donation_month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], help_text='Month of last blood donation (optional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_donation_year',
            field=models.CharField(blank=True, help_text='Year of last blood donation (optional)', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(help_text='Must be unique and at least 10 digits', max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture (max 5MB)', null=True, upload_to='donor_images/'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of registration'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['blood_group'], name='roktodanbdw_blood_g_58de83_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['thana'], name='roktodanbdw_thana_9ba631_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['district'], name='roktodanbdw_distric_788d64_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['is_active', 'is_available'], name='roktodanbdw_is_acti_31dd27_idx'),
        ),
    ]
