# Generated by Django 5.2.6 on 2025-09-08 05:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roktodanbdweb', '0005_alter_recipient_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(default='Dhaka, Bangladesh', max_length=200)),
                ('blood_group', models.CharField(max_length=5)),
                ('amount', models.IntegerField(default=450, help_text='Amount in ml')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='roktodanbdweb.donor')),
            ],
            options={
                'verbose_name': 'Donation History',
                'verbose_name_plural': 'Donation Histories',
                'ordering': ['-donation_date'],
            },
        ),
    ]
