# Generated by Django 5.2.5 on 2025-09-09 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roktodanbdweb', '0006_donationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group_needed', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('units_needed', models.PositiveIntegerField(default=1, help_text='Number of blood units needed')),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('hospital_name', models.CharField(max_length=200)),
                ('hospital_address', models.TextField()),
                ('thana', models.CharField(choices=[('Adabar', 'Adabar'), ('Badda', 'Badda'), ('Banani', 'Banani'), ('Baridhara', 'Baridhara'), ('Dhanmondi', 'Dhanmondi'), ('Gulshan', 'Gulshan'), ('Hatirjheel', 'Hatirjheel'), ('Kafrul', 'Kafrul'), ('Kalabagan', 'Kalabagan'), ('Khilgaon', 'Khilgaon'), ('Khilkhet', 'Khilkhet'), ('Mirpur', 'Mirpur'), ('Mohammadpur', 'Mohammadpur'), ('Motijheel', 'Motijheel'), ('New Market', 'New Market'), ('Old Dhaka', 'Old Dhaka'), ('Pallabi', 'Pallabi'), ('Ramna', 'Ramna'), ('Rampura', 'Rampura'), ('Sabujbagh', 'Sabujbagh'), ('Shah Ali', 'Shah Ali'), ('Sher-e-Bangla Nagar', 'Sher-e-Bangla Nagar'), ('Tejgaon', 'Tejgaon'), ('Uttara', 'Uttara'), ('Wari', 'Wari')], max_length=50)),
                ('district', models.CharField(default='Dhaka', max_length=50)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.PositiveIntegerField()),
                ('medical_condition', models.CharField(blank=True, max_length=200)),
                ('needed_by_date', models.DateTimeField()),
                ('additional_notes', models.TextField(blank=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('alternative_contact', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='roktodanbdweb.recipient')),
            ],
            options={
                'verbose_name': 'Blood Request',
                'verbose_name_plural': 'Blood Requests',
                'ordering': ['-urgency_level', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('accept', 'Accept'), ('refuse', 'Refuse')], max_length=10)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for the response')),
                ('preferred_donation_time', models.DateTimeField(blank=True, null=True)),
                ('availability_notes', models.TextField(blank=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_responses', to='roktodanbdweb.bloodrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='roktodanbdweb.donor')),
            ],
            options={
                'verbose_name': 'Donor Response',
                'verbose_name_plural': 'Donor Responses',
                'ordering': ['-response_date'],
            },
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['blood_group_needed'], name='roktodanbdw_blood_g_683878_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['thana'], name='roktodanbdw_thana_1668b5_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['status'], name='roktodanbdw_status_b9ea2d_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['urgency_level'], name='roktodanbdw_urgency_ed6f92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='donorresponse',
            unique_together={('donor', 'blood_request')},
        ),
    ]
